name: Deploy Playground

on: # 触发条件
  push:
    branches:
      - main # 当 main 分支收到推送时触发
  workflow_dispatch: # 允许手动触发

jobs:
  deploy:
    uses: byronogis/workflows/.github/workflows/deploy.yml@v1
    with:
      dist: docs/dist
    permissions:
      contents: read
      pages: write
      id-token: write
